/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiIntakeChatRouteImport } from './routes/api/intake/chat'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppIntakeRouteImport } from './routes/_authenticated/app.intake'
import { Route as AuthenticatedAppHistoryRouteImport } from './routes/_authenticated/app.history'
import { Route as AuthenticatedAppIntakeSessionIdRouteImport } from './routes/_authenticated/app.intake.$sessionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiIntakeChatRoute = ApiIntakeChatRouteImport.update({
  id: '/api/intake/chat',
  path: '/api/intake/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIntakeRoute = AuthenticatedAppIntakeRouteImport.update({
  id: '/app/intake',
  path: '/app/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppHistoryRoute = AuthenticatedAppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIntakeSessionIdRoute =
  AuthenticatedAppIntakeSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedAppIntakeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/intake': typeof AuthenticatedAppIntakeRouteWithChildren
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/api/intake/chat': typeof ApiIntakeChatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/intake/$sessionId': typeof AuthenticatedAppIntakeSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/history': typeof AuthenticatedAppHistoryRoute
  '/app/intake': typeof AuthenticatedAppIntakeRouteWithChildren
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/api/intake/chat': typeof ApiIntakeChatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/intake/$sessionId': typeof AuthenticatedAppIntakeSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app/history': typeof AuthenticatedAppHistoryRoute
  '/_authenticated/app/intake': typeof AuthenticatedAppIntakeRouteWithChildren
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/api/intake/chat': typeof ApiIntakeChatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/intake/$sessionId': typeof AuthenticatedAppIntakeSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app/history'
    | '/app/intake'
    | '/app/profile'
    | '/api/intake/chat'
    | '/app/'
    | '/app/intake/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/history'
    | '/app/intake'
    | '/app/profile'
    | '/api/intake/chat'
    | '/app'
    | '/app/intake/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/app/history'
    | '/_authenticated/app/intake'
    | '/_authenticated/app/profile'
    | '/api/intake/chat'
    | '/_authenticated/app/'
    | '/_authenticated/app/intake/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiIntakeChatRoute: typeof ApiIntakeChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/intake/chat': {
      id: '/api/intake/chat'
      path: '/api/intake/chat'
      fullPath: '/api/intake/chat'
      preLoaderRoute: typeof ApiIntakeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/intake': {
      id: '/_authenticated/app/intake'
      path: '/app/intake'
      fullPath: '/app/intake'
      preLoaderRoute: typeof AuthenticatedAppIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/history': {
      id: '/_authenticated/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AuthenticatedAppHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/intake/$sessionId': {
      id: '/_authenticated/app/intake/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/intake/$sessionId'
      preLoaderRoute: typeof AuthenticatedAppIntakeSessionIdRouteImport
      parentRoute: typeof AuthenticatedAppIntakeRoute
    }
  }
}

interface AuthenticatedAppIntakeRouteChildren {
  AuthenticatedAppIntakeSessionIdRoute: typeof AuthenticatedAppIntakeSessionIdRoute
}

const AuthenticatedAppIntakeRouteChildren: AuthenticatedAppIntakeRouteChildren =
  {
    AuthenticatedAppIntakeSessionIdRoute: AuthenticatedAppIntakeSessionIdRoute,
  }

const AuthenticatedAppIntakeRouteWithChildren =
  AuthenticatedAppIntakeRoute._addFileChildren(
    AuthenticatedAppIntakeRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppHistoryRoute: typeof AuthenticatedAppHistoryRoute
  AuthenticatedAppIntakeRoute: typeof AuthenticatedAppIntakeRouteWithChildren
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppHistoryRoute: AuthenticatedAppHistoryRoute,
  AuthenticatedAppIntakeRoute: AuthenticatedAppIntakeRouteWithChildren,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiIntakeChatRoute: ApiIntakeChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
